# Generated by Django 4.1.1 on 2022-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('bakery', 'bakery'), ('meat', 'meat'), ('healthy living', 'healthy living'), ('baby care', 'baby care'), ('health wellness', 'health wellness'), ('home cleaning', 'home cleaning'), ('cooking essentials', 'cooking essentials'), ('fruit vegetable', 'fruit vegetable'), ('other', 'other')], default='other', max_length=150)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
