# Generated by Django 4.1.1 on 2022-09-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirana_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
